name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - "1.11"
        - "1.17"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: make ci-test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.17"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: make cross-build
    - run: make dist
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist/*.tar.gz
          dist/*.zip

  release-test:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
    - run: find .

  release:
    needs: [test, build]
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.tar.gz
          dist/*.zip
